version: '3.6'

volumes:
  nginx_conf_d: {}
  nginx_vhost_d: {}
  nginx_certs: {}
  nginx_html: {}

services:
  # region https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion#separate-containers
  nginx:
    image: nginx:1.15.12-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - nginx_conf_d:/etc/nginx/conf.d
      - nginx_vhost_d:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs:ro
    ports:
      - 80:80
      - 443:443

  nginx-gen:
    image: webyneter/nginx-gen:0.7.3
    container_name: nginx-gen
    restart: unless-stopped
    volumes:
      - nginx_conf_d:/etc/nginx/conf.d
      - nginx_vhost_d:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.11
    container_name: nginx-letsencrypt
    restart: unless-stopped
    depends_on:
      - nginx
      - nginx-gen
    volumes:
      - nginx_conf_d:/etc/nginx/conf.d
      - nginx_vhost_d:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
  # endregion
