---

- fail:
    msg: "'root_dir_path' is not defined"
  when: root_dir_path is not defined

- fail:
    msg: "'stack_to_launch' must equal 'nginx' or 'traefik'"
  when: stack_to_launch not in [nginx, traefik]

- fail:
    msg: "'letsencrypt_email' is not defined"
  when: stack_to_launch == traefik and letsencrypt_email is not defined
