---

- include_tasks: check_required_vars.yml

- name: "Create {{ project_dir_path }}/"
  file:
    path: "{{ project_dir_path }}"
    recurse: yes
    state: directory

- name: "Copy docker-compose files to {{ project_dir_path }}/"
  copy:
    src: "{{ item }}"
    dest: "{{ project_dir_path }}"
  loop:
  - ./docker-compose.yml

- name: Re/start stack
  command: >
    docker-compose
      --project-name "{{ project_name }}"
      --file "{{ project_dir_path }}/docker-compose.yml"
      up
      --detach
      --force-recreate
