---

- include_tasks: check_vars.yml

- name: "Create {{ project_dir_path }}/"
  file:
    path: "{{ project_dir_path }}"
    recurse: yes
    state: directory

- name: "Copy {{ stack_to_launch }} files to {{ project_dir_path }}/"
  copy:
    src: "{{ item }}"
    dest: "{{ project_dir_path }}"
  loop:
    - "./{{ stack_to_launch }}.yml"

- name: "Launch {{ stack_to_launch }} stack"
  environment: "{{ lookup('vars', stack_to_launch + '_environment')}}"
  command: >
    docker-compose
      --project-name "{{ project_name }}"
      --file "{{ project_dir_path }}/{{ stack_to_launch }}.yml"
      up
      --detach
      --force-recreate
